const dataBase = [
    {
        id: '1',
        img: './Imagens/FNAF.jpg',
        titulo: 'Box Five Nights at Freddy’s',
        tags: ['Fantasia', 'Ficção', 'Games'],
        descricao: 'O game Five Nights at Freddy’s conquistou legiões de fãs no mundo todo, e a série de livros seguiu a mesma trilha de sucesso. Escritos por Scott Cawthon, criador do jogo...',
        valor: 149.75,
    },
    {   
        id: '2',
        img: './Imagens/Sherlock_Holmes.jpg',
        titulo: 'Box Sherlock Holmes',
        tags: ['Fantasia', 'Ficção', 'Mistério'],
        descricao: 'Em 1887, o escritor escocês sir Arthur Conan Doyle criou Sherlock Holmes, o infalível detetive a quem os agentes da Scotland Yard recorriam para solucionar os mistérios mais intrigantes da Inglaterra vitoriana. Desde então...',
        valor: 139.95,
    },
    {   
        id: '3',
        img: './Imagens/Harry_Potter.jpg',
        titulo: 'Box Harry Potter com Marcadores',
        tags: ['Fantasia', 'Magia'],
        descricao: 'Maior fenômeno editorial de todos os tempos, com mais de 450 milhões de exemplares vendidos em 70 idiomas, a série Harry Potter chega às prateleiras em mais essa edição de colecionador. Os sete livros da saga criada por J. K. Rowling...',
        valor: 223.92,
    },
    {   
        id: '4',
        img: './Imagens/Percy_Jacksson.jpg',
        titulo: 'Box Percy Jackson e os Olimpianos',
        tags: ['Fantasia', 'Romance'],
        descricao: 'Combinando mitologia grega e muita aventura, a saga do menino Percy Jackson, que aos 12 anos descobre que é um semideus, filho de Poseidon, tornou-se um fenômeno mundial. Foram...',
        valor: 219.65,
    },
    {   
        id: '5',
        img: './Imagens/Guerras_Secretas.jpg',
        titulo: 'Box Marvel - Guerras Secretas',
        tags: ['Fantasia', 'Quadrinhos'],
        descricao: 'GUERRA CIVIL Homem de Ferro e Capitão América: dois membros essenciais para os Vingadores, a maior equipe de super-heróis do mundo. Quando uma trágica batalha...',
        valor: 55.92,
    },
    {   
        id: '6',
        img: './Imagens/Jogos_Vorazes.jpg',
        titulo: 'Box Jogos Vorazes',
        tags: ['Fantasia', 'Ficção', 'Romance'],
        descricao: 'Box rígido com três livros em brochura, com orelha, acompanha um pôster e três marcadores. Ambientada num futuro sombrio, a saga Jogos Vorazes foi pioneira de uma tendência que ganhou força na literatura jovem nos últimos anos: a dos romances...',
        valor: 131.92,
    },
];